[features]
seeds = false
skip-lint = false
[programs.localnet]
bridge_contract = "7oikCXiFBK5cqy4AJGrjaJNVhLNNB2eKgjxQXVHukuj4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/shrey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
